/**
 * The JSON contract as it exists on disk — contract version 1.
 *
 * These types describe the file format and nothing else. They are deliberately
 * permissive: every collection is optional and nothing is validated on load
 * (R-MODEL-01), because the same files are hand-authored, generated by
 * `tools/spla-arch`, and written back by this editor.
 *
 * Do not use these types outside `wire.ts`. Everything above the wire layer
 * works with the in-memory tree in `document.ts`. That separation is what keeps
 * a future contract v2 (see docs/CONTRACT_V2.md) a change to two files rather
 * than to the whole codebase.
 */

export interface WireZoneStyle {
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  strokeDasharray?: string;
  headerBg?: string;
}

export interface WireMetadata {
  type?: string;
  description?: string;
  codeRef?: string;
  responsibilities?: string[];
  [key: string]: unknown;
}

export interface WireZone {
  id: string;
  name?: string;
  type?: string;
  semanticId?: string;
  tags?: string[];
  x: number;
  y: number;
  width: number;
  height: number;
  style?: WireZoneStyle;
  metadata?: WireMetadata;
}

export interface WireNode {
  id: string;
  label?: string;
  type?: string;
  /** Declared parent zone id. Null, absent, or dangling all mean "not declared". */
  zone?: string | null;
  x: number;
  y: number;
  width: number;
  height: number;
  tags?: string[];
  metadata?: WireMetadata;
}

export interface WireEdge {
  id: string;
  from: string;
  to: string;
  label?: string;
  type?: string;
}

export interface WireView {
  id: string;
  name?: string;
  icon?: string;
  description?: string;
  highlightZones?: string[];
  highlightNodes?: string[];
}

export interface WireDocumentMetadata {
  title?: string;
  layout?: string;
  description?: string;
  [key: string]: unknown;
}

export interface WireDocument {
  metadata?: WireDocumentMetadata;
  views?: WireView[];
  zones?: WireZone[];
  nodes?: WireNode[];
  edges?: WireEdge[];
}
