/**
 * SPLA Diagram Project Format types.
 *
 * Describes the single unified project structure on disk:
 * - project.json (manifest)
 * - entities.json (entities catalog)
 * - relations.json (relations catalog)
 * - text.<lang>.json (localized descriptions and names)
 * - views/<view_id>.view.json (view layouts: zones, nodes, edges)
 */

import type { ParsedTextCatalog } from "./text-provenance.js";

export interface WireMetadata {
  type?: string;
  kind?: string;
  description?: string;
  codeRef?: string;
  responsibilities?: string[];
  [key: string]: unknown;
}

export interface WireZone {
  id: string;
  name?: string;
  type?: string;
  semanticId?: string;
  tags?: string[];
  x: number;
  y: number;
  width: number;
  height: number;
  styleId?: string;
  metadata?: WireMetadata;
}

export interface WireNode {
  id: string;
  label?: string;
  type?: string;
  /** Declared parent zone id. Null, absent, or dangling all mean "not declared". */
  zone?: string | null;
  x: number;
  y: number;
  width: number;
  height: number;
  tags?: string[];
  styleId?: string;
  metadata?: WireMetadata;
}

export interface WireEdge {
  id: string;
  from: string;
  to: string;
  label?: string;
  type?: string;
  styleId?: string;
  points?: Array<{ x: number; y: number }>;
}

export interface WireView {
  id: string;
  name?: string;
  icon?: string;
  description?: string;
  highlightZones?: string[];
  highlightNodes?: string[];
}

export interface WireDocumentMetadata {
  title?: string;
  subtitle?: string;
  layout?: string;
  description?: string;
  [key: string]: unknown;
}

export interface WireDocument {
  metadata?: WireDocumentMetadata;
  views?: WireView[];
  zones?: WireZone[];
  nodes?: WireNode[];
  edges?: WireEdge[];
  bundle?: ProjectBundle;
}

// ------------------------------------------------------------- Project Bundle

export interface EntityEntry {
  id: string;
  name: string;
  kind: string;
  origin?: "code" | "authored";
  status?: "present" | "missing" | "planned";
  namespace?: string;
  codeRef?: string;
  members?: string[];
  [key: string]: unknown;
}

export interface EntityCatalog {
  entities: EntityEntry[];
}

export interface RelationEvidence {
  codeRef?: string;
  symbol?: string;
  line?: number;
}

export interface RelationEntry {
  id: string;
  from: string;
  to: string;
  type: string;
  relation?: string;
  label?: string;
  styleId?: string;
  origin?: "code" | "authored";
  status?: "present" | "missing";
  evidence?: RelationEvidence[];
  points?: Array<{ x: number; y: number }>;
  [key: string]: unknown;
}

export interface RelationCatalog {
  relations: RelationEntry[];
}

/**
 * In-memory text: plain strings, because that is what every consumer wants.
 * The provenance that accompanies them on disk lives in `ProjectBundle.textFiles`
 * (see `text-provenance.ts`).
 */
export interface TextCatalog {
  entries: Record<string, { name?: string; title?: string; doc?: string; description?: string }>;
}

/**
 * Authored vocabulary of relation types.
 *
 * A separate file rather than entries in `entities.json` because that catalogue
 * is partly generated from code: regeneration would drown a dozen hand-written
 * lines in churn. A relation type is also never placed on a canvas, which is
 * what `entities.json` is a registry of.
 *
 * Name and description live in the text catalogues under the type's `rt_` id.
 */
export interface RelationTypeEntry {
  id: string;
  /** Generated by `sync` from code, or written by a human. */
  origin?: "code" | "authored";
  styleId?: string;
  [key: string]: unknown;
}

export interface RelationTypeCatalog {
  relationTypes: RelationTypeEntry[];
}

export interface ProjectManifest {
  id: string;
  title: string;
  subtitle?: string;
  defaultView?: string;
  languages?: string[];
  views?: string[];
  [key: string]: unknown;
}

export interface ViewZonePlacement {
  id: string;
  container?: string | null;
  parent?: string | null;
  x: number;
  y: number;
  width: number;
  height: number;
  styleId?: string;
  collapsed?: boolean;
}

export interface ViewNodePlacement {
  id?: string;
  entity?: string;
  container?: string | null;
  zone?: string | null;
  x: number;
  y: number;
  width?: number;
  height?: number;
  styleId?: string;
}

export interface ViewEdgePlacement {
  id: string;
  from: string;
  to: string;
  type?: string;
  relation?: string;
  label?: string;
  styleId?: string;
  points?: Array<{ x: number; y: number }>;
}

export interface ViewDocument {
  id: string;
  project: string;
  /**
   * What this view's containers classify — `axis_layer`, `axis_project`,
   * `axis_security_zone`, ... Required: without it, a node sitting inside a
   * rectangle is unreadable, because "belongs to this assembly", "runs in this
   * process" and "moved here so the arrows don't cross" look identical.
   *
   * Two views on different axes may legitimately put one node in different
   * containers. Two views on the same axis may not — that is a contradiction,
   * and the model check reports it.
   */
  axis?: string;
  zones?: ViewZonePlacement[];
  nodes?: ViewNodePlacement[];
  placements?: ViewNodePlacement[];
  edges?: ViewEdgePlacement[];
  [key: string]: unknown;
}

export interface ProjectBundle {
  project: ProjectManifest;
  entities: EntityCatalog;
  relations: RelationCatalog;
  text: TextCatalog;
  textRegistries?: Record<string, TextCatalog>;
  /**
   * Provenance of each text catalogue as loaded, kept so that saving can leave
   * untouched values exactly as they were and re-stamp only what changed.
   */
  textFiles?: Record<string, ParsedTextCatalog>;
  relationTypes?: RelationTypeCatalog;
  view: ViewDocument;
}
