import type { CommandDefinition } from "./types.js";

export function createBuiltinCommands(): CommandDefinition[] {
  return [
    // ----------------------------------------------------------------- File
    {
      id: "file.save",
      title: "Сохранить",
      description: "Сохранить изменения схемы и стилей на сервере",
      icon: "💾",
      category: "File",
      shortcut: "Ctrl+S",
      keyTip: "S",
      isEnabled: (ctx) => ctx.editor.hasUnsavedChanges,
      execute: (ctx) => ctx.io.save(),
    },
    {
      id: "file.open",
      title: "Открыть JSON…",
      description: "Открыть файл схемы JSON с диска",
      icon: "📂",
      category: "File",
      shortcut: "Ctrl+O",
      keyTip: "O",
      execute: (ctx) => ctx.io.openFile(),
    },
    {
      id: "file.export.drawio",
      title: ".drawio",
      description: "Экспортировать схему в формат diagrams.net XML",
      icon: "📐",
      category: "File",
      keyTip: "D",
      isEnabled: (ctx) => ctx.document !== null,
      execute: (ctx) => ctx.io.exportDrawio(),
    },
    {
      id: "file.code.toggle",
      title: "Код схемы",
      description: "Просмотр и прямое редактирование JSON модели диаграммы",
      icon: "📄",
      category: "File",
      keyTip: "J",
      isEnabled: (ctx) => ctx.document !== null,
      execute: (ctx) => ctx.io.toggleJsonModal(),
    },

    // ----------------------------------------------------------------- Edit
    {
      id: "edit.undo",
      title: "Отменить",
      description: "Отменить последнее действие",
      icon: "↶",
      category: "Edit",
      shortcut: "Ctrl+Z",
      keyTip: "U",
      isEnabled: (ctx) => ctx.history.canUndo,
      execute: (ctx) => ctx.editor.undo(),
    },
    {
      id: "edit.redo",
      title: "Повторить",
      description: "Повторить отмененное действие",
      icon: "↷",
      category: "Edit",
      shortcut: "Ctrl+Y, Ctrl+Shift+Z",
      keyTip: "R",
      isEnabled: (ctx) => ctx.history.canRedo,
      execute: (ctx) => ctx.editor.redo(),
    },
    {
      id: "edit.delete",
      title: "Удалить",
      description: "Удалить выбранный элемент или связь",
      icon: "🗑",
      category: "Edit",
      shortcut: "Delete, Backspace",
      keyTip: "X",
      isEnabled: (ctx) => ctx.selection.hasSelection,
      execute: (ctx) => ctx.editor.deleteSelection(),
    },

    // -------------------------------------------------------------- Diagram
    {
      id: "diagram.block.add",
      title: "Блок",
      description: "Создать новый компонентный блок на схеме",
      icon: "➕",
      category: "Diagram",
      shortcut: "Ctrl+Shift+B",
      keyTip: "B",
      isEnabled: (ctx) => ctx.document !== null,
      execute: (ctx) => ctx.editor.createNode(),
    },
    {
      id: "diagram.zone.add",
      title: "Зона",
      description: "Создать новую область/слой (контейнер)",
      icon: "📦",
      category: "Diagram",
      shortcut: "Ctrl+Shift+Z",
      keyTip: "Z",
      isEnabled: (ctx) => ctx.document !== null,
      execute: (ctx) => ctx.editor.createZone(),
    },
    {
      id: "diagram.ports.set",
      title: "Причаливание связей",
      description: "Установить режим размещения концов связей по сторонам блоков",
      icon: "⚓",
      category: "Diagram",
      keyTip: "P",
      execute: (ctx, args) => ctx.editor.applyPortAssigner(String(args || "uniform")),
    },

    // ----------------------------------------------------------------- View
    {
      id: "view.grid.toggle",
      title: "Точки сетки",
      description: "Показать или скрыть координатную сетку",
      icon: "▦",
      category: "View",
      shortcut: "Ctrl+'",
      keyTip: "G",
      isChecked: (ctx) => ctx.canvas.hostElement.classList.contains("with-grid"),
      execute: (ctx) => {
        const next = !ctx.canvas.hostElement.classList.contains("with-grid");
        ctx.editor.applyToggle("grid", next);
      },
    },
    {
      id: "view.snap.toggle",
      title: "Привязка",
      description: "Привязка координат к шагу 10px при перетаскивании",
      icon: "🧲",
      category: "View",
      shortcut: "Ctrl+Shift+S",
      keyTip: "N",
      isChecked: (ctx) => ctx.canvas.gridStep > 0,
      execute: (ctx) => {
        const next = ctx.canvas.gridStep === 0;
        ctx.editor.applyToggle("snap", next);
      },
    },
    {
      id: "view.zoom.in",
      title: "Приблизить",
      description: "Увеличить масштаб отображения схемы",
      icon: "➕",
      category: "View",
      shortcut: "Ctrl+=",
      keyTip: "+",
      execute: (ctx) => ctx.canvas.zoomBy(1.2),
    },
    {
      id: "view.zoom.out",
      title: "Отдалить",
      description: "Уменьшить масштаб отображения схемы",
      icon: "➖",
      category: "View",
      shortcut: "Ctrl+-",
      keyTip: "-",
      execute: (ctx) => ctx.canvas.zoomBy(0.8),
    },
    {
      id: "view.zoom.reset",
      title: "100%",
      description: "Сбросить масштаб в 100%",
      icon: "🔍",
      category: "View",
      shortcut: "Ctrl+0",
      keyTip: "0",
      execute: (ctx) => ctx.canvas.resetZoom(),
    },
    {
      id: "view.zoom.fit",
      title: "Вписать",
      description: "Вписать содержимое диаграммы в экран",
      icon: "⛶",
      category: "View",
      shortcut: "Ctrl+Shift+0",
      keyTip: "F",
      execute: (ctx) => ctx.canvas.fit(),
    },
    {
      id: "view.theme.set",
      title: "Тема",
      description: "Переключить цветовую тему оформления",
      icon: "🎨",
      category: "View",
      keyTip: "T",
      execute: (ctx, args) => ctx.editor.applyTheme(String(args || "cream")),
    },
    {
      id: "view.lang.set",
      title: "Язык данных",
      description: "Переключить язык данных схемы (RU / EN)",
      icon: "🌐",
      category: "View",
      keyTip: "K",
      execute: (ctx, args) => ctx.editor.applyDataLang(String(args || "ru")),
    },
    {
      id: "view.edges.toggleStructure",
      title: "Структурные связи",
      description: "Показать/скрыть связи порождения (implements, extends, composes)",
      icon: "🔗",
      category: "View",
      keyTip: "E",
      isChecked: (ctx) => !ctx.canvas.isEdgeFamilyHidden("structure"),
      execute: (ctx) => {
        const isHidden = ctx.canvas.isEdgeFamilyHidden("structure");
        ctx.editor.applyToggle("structure-edges", isHidden);
      },
    },

    // --------------------------------------------------------------- Panels
    {
      id: "panel.properties.toggle",
      title: "Свойства",
      description: "Показать или скрыть панель свойств",
      icon: "⚙️",
      category: "Panels",
      shortcut: "Alt+1",
      keyTip: "P1",
      isChecked: (ctx) => ctx.panels.isOpen("properties"),
      execute: (ctx) => ctx.panels.toggle("properties"),
    },
    {
      id: "panel.relations.toggle",
      title: "Связи",
      description: "Показать или скрыть панель связей",
      icon: "🔗",
      category: "Panels",
      shortcut: "Alt+2",
      keyTip: "P2",
      isChecked: (ctx) => ctx.panels.isOpen("relations"),
      execute: (ctx) => ctx.panels.toggle("relations"),
    },
    {
      id: "panel.filters.toggle",
      title: "Фильтры",
      description: "Показать или скрыть панель ракурсов и фильтрации",
      icon: "🔍",
      category: "Panels",
      shortcut: "Alt+3",
      keyTip: "P3",
      isChecked: (ctx) => ctx.panels.isOpen("filters"),
      execute: (ctx) => ctx.panels.toggle("filters"),
    },
    {
      id: "panel.styles.toggle",
      title: "Стили",
      description: "Показать или скрыть панель библиотеки стилей",
      icon: "🎨",
      category: "Panels",
      shortcut: "Alt+4",
      keyTip: "P4",
      isChecked: (ctx) => ctx.panels.isOpen("styles"),
      execute: (ctx) => ctx.panels.toggle("styles"),
    },
    {
      id: "panel.catalog.toggle",
      title: "Каталог схем",
      description: "Показать или скрыть панель каталога схем",
      icon: "📚",
      category: "Panels",
      shortcut: "Alt+5",
      keyTip: "P5",
      isChecked: (ctx) => ctx.panels.isOpen("catalog"),
      execute: (ctx) => ctx.panels.toggle("catalog"),
    },
    {
      id: "panel.base.toggle",
      title: "База сущностей",
      description: "Показать или скрыть панель базы сущностей проекта",
      icon: "🗄️",
      category: "Panels",
      shortcut: "Alt+6",
      keyTip: "P6",
      isChecked: (ctx) => ctx.panels.isOpen("base"),
      execute: (ctx) => ctx.panels.toggle("base"),
    },

    // ------------------------------------------------------------ Workspace
    {
      id: "workspace.layout.reset",
      title: "Сброс раскладки",
      description: "Восстановить исходное расположение панелей рабочей области",
      icon: "🔄",
      category: "Workspace",
      keyTip: "WR",
      execute: (ctx) => ctx.workspace.resetLayout(),
    },
  ];
}
